name: sbdv_web
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.1
  auto_route: ^9.3.0+1
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  retrofit: ^4.4.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.2.4
  rive: ^0.13.20
  data_table_2: ^2.5.18
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
