name: Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - master   # Production deployment
      - staging # Staging deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BASE_URL=${{ secrets.BASE_URL_PROD }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "BASE_URL=${{ secrets.BASE_URL_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Build Flutter Web
        run: flutter build web --dart-define=baseUrl=$BASE_URL

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "$${{ secrets.FIREBASE_TOKEN }}"
